[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"
deca-VampireCommandFramework = "0.9.0"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["1-0-update", "mods", "server"]

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[package]
namespace = "zfolmt"
name = "Sanguis"
versionNumber = "1.0.0"
description = "Reward players for being online with optional daily login bonus!"
websiteUrl = "https://github.com/mfoltz/Sanguis"
containsNsfwContent = false
